# Generated by Django 3.2.4 on 2021-06-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ACCEPTED', 'Accepted')], default='IN_PROGRESS', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'User Informations',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.DateField(verbose_name='vehicle year make')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='vehicle model')),
                ('vehicle_num', models.CharField(max_length=5, verbose_name='vehicle no.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.userinformation')),
            ],
            options={
                'verbose_name_plural': 'vehicle details',
            },
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_datetime', models.DateTimeField(verbose_name='date and time of accident')),
                ('accident_location', models.CharField(max_length=150, verbose_name='Location')),
                ('accident_losstype', models.CharField(choices=[('OWN_DAMAGE', 'Own Damage'), ('KNOCK_FOR_KNOCK', 'Knock for Knock'), ('WINDSCREEN_DAMAGE', 'Windscreen Damage'), ('THIEF', 'Thief')], max_length=30)),
                ('accident_description', models.TextField(verbose_name='description of loss')),
                ('accident_police_lodged', models.BooleanField(verbose_name='police report lodged?')),
                ('accident_injured', models.BooleanField(verbose_name='anybody injured?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.userinformation')),
            ],
            options={
                'verbose_name_plural': 'loss details',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docFile', models.FileField(upload_to='assets/documents', verbose_name='Document File')),
                ('photo', models.ImageField(upload_to='assets/photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.userinformation')),
            ],
            options={
                'verbose_name_plural': 'claim document details',
            },
        ),
    ]
